#!/bin/bash

# https://stackoverflow.com/questions/10478210/limit-git-diff-to-one-or-more-functions
usage='grit gofuncdiff 009e75 8b7a14 ./staging.go "Filter"'

cmd=$1
shift 1
if [ -z "${cmd}" ]; then
	echo $usage
elif [ $cmd = "gofuncdiff" ]; then
	git show "$1:$3" | awk -f ~/scripts/get_go_func.awk -v f=$4 > /tmp/tmpv1.go
	git show "$2:$3" | awk -f ~/scripts/get_go_func.awk -v f=$4 > /tmp/tmpv2.go
	git diff -W --no-index /tmp/tmpv1.go /tmp/tmpv2.go
else 
	echo $usage
fi
